### ISSUE TITLE
Using the MasterDiscovery::getMaster() call with an authenticated redis throws an exception

### ISSUE THREAD

**Issue by forceedge01** [jamescauwelier/PSRedis#23]
The exception is thrown that it requires a password when doing the discovery for the sentinel master. From what we can see so far, the discovery does not require a password even for a password protected redis sentinel server.

Had a look a bit deeper in the code, the getMaster call fetches the master correctly, but then does another call `isMaster()` in the `MasterDiscovery.php` file that throws this error. Wondering why do we need to check again if the `getMaster()` call returns the master sentinel config?

Code that seems to have an issue is: MasterDiscovery.php, Line: 127.

**Comment by forceedge01** [comment]
<img width="1146" alt="screen shot 2016-05-25 at 17 26 26" src="https://cloud.githubusercontent.com/assets/1619816/15547920/fa6785fc-229d-11e6-9721-ca4f158e5d6b.png">

**Comment by forceedge01** [comment]
Fetching the sentinel config does not require authentication, but the second call `isMaster()` does require authentication where it fails.

**Comment by jamescauwelier** [comment]
@forceedge01 See the [guidelines for clients](http://redis.io/topics/sentinel-clients) which explains how the code should react.  The checking of the role in the master is consistent with the specs in the link above.  This is because between finding the master and connecting the master, the role of that node could have changed.

I don't understand the exact problem.  Is the code not using the auth details properly in the connection to the master or does it require authentication when it shouldn't.  Can you elaborate on your setup?  I'll be more than happy to get a fix ready for you!

**Comment by forceedge01** [comment]
@jamescauwelier Sorry for the delayed reply, I must have confused you. Here is some more information. I understand that between the finding and connecting with the master, the role could change. But the first call i.e the find does not require a password to get that information while the second call does require authentication. I am not sure if this is an issue with your package but it is a blocker for us at the moment due to the authentication required for the second call (role). The client object that holds the `isMaster` call does not accept a password and can't connect to our redis server.

**Comment by forceedge01** [comment]
To answer you more clearly:
1 - Find sentinel master (does not require authentication).
2 - Ask the master its role (does require authentication).

The solution i think would be to allow a password to be set during connection?

**Comment by jamescauwelier** [comment]
You can use a custom client factory when constructing your ```PredisClientAdapter```.  The factory used should implement [the correct interface](https://github.com/jamescauwelier/PSRedis/blob/develop/lib/PSRedis/Client/Adapter/Predis/PredisClientFactory.php) and you can pass your authentication details in there either hardcoded or injected in the constructor.

"[Customizing the adapter](https://github.com/jamescauwelier/PSRedis#customizing-the-adapter)" shows first the creation of such a factory provided with the library, but as said you can create your own authenticated one.  This is probably a common requirement so we could add it to the library?  Feel free to do  a PR if you create this because it might take a few days if you wait on me.  The writing is not hard at all, but I like unit tests to go with it.

**Comment by jamescauwelier** [comment]
I'll assume this has fixed your issue @forceedge01 ?
